server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    banner-mode: off

  application:
    name: gaming-api

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/gaming}
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME:gaming-admin}
    password: ${DATASOURCE_PASSWORD:s3cr3t}
  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
  data:
    jdbc:
      dialect: postgresql
    redis:
      host: localhost
      port: 6379

  cache:
    type: ${REDIS_HOSTNAME:localhost}
    redis:
      time-to-live: 60m