server:
  port: 8080

spring:
  application:
    name: gaming-api

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/gaming}
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME:gaming-admin}
    password: ${DATASOURCE_PASSWORD:s3cr3t}
  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    jdbc:
      dialect: postgresql

logging:
  level:
    org.flywaydb: DEBUG
    db.migration: DEBUG